// ─── Tier Definitions ─────────────────────────────────────────────
const TIERS = {
  mid: {
    id: 'mid',
    emoji: '💰',
    label: 'Godt alternativ',
    sublabel: 'Lignende kvalitet, anden pris eller fiber',
    color: '#4a5e3a',
  },
  budget: {
    id: 'budget',
    emoji: '✂️',
    label: 'Billigere alternativ',
    sublabel: 'Markant billigere — gode resultater',
    color: '#3a4e6e',
  },
  premium: {
    id: 'premium',
    emoji: '🏆',
    label: 'Opgradering',
    sublabel: 'Mere eksklusivt end originalen',
    color: '#7a5c2e',
  },
};

// ─── Yarn Weight Categories ────────────────────────────────────────
const WEIGHTS = {
  lace:      { label: 'Lace / 0-ply',         gaugeRange: [33, 40], needle: '1.5–2.25 mm' },
  fingering: { label: 'Fingering / 2-ply',     gaugeRange: [27, 32], needle: '2.25–3.25 mm' },
  sport:     { label: 'Sport / 4-ply',         gaugeRange: [23, 26], needle: '3.25–3.75 mm' },
  DK:        { label: 'DK / Double Knit',      gaugeRange: [21, 24], needle: '3.5–4.5 mm' },
  worsted:   { label: 'Worsted / Aran',        gaugeRange: [16, 20], needle: '4.5–5.5 mm' },
  bulky:     { label: 'Bulky / Chunky',        gaugeRange: [12, 15], needle: '5.5–8 mm' },
  superbulky:{ label: 'Super Bulky',           gaugeRange: [7,  11], needle: '8–12 mm' },
};

// ─── Yarn Database ─────────────────────────────────────────────────
const YARNS = [

  {
    id: 'krea-deluxe-organic-cotton',
    name: 'Organic Cotton',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Organic Cotton from Krea Deluxe. Composition: 100 % bomuld.',
    certifications: ['GOTS'],
  },

  {
    id: 'krea-deluxe-deluxe-silk-mohair',
    name: 'Deluxe silk mohair',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: null, needle_mm: 4.0 },
    fiber: [{ name: 'silke', pct: 45 }, { name: 'mohair', pct: 33 }, { name: 'baby alpaca', pct: 22 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Deluxe silk mohair from Krea Deluxe. Composition: 45% silke, 33% mohair, 22% baby alpaca.',
    certifications: ['Cruelty free?'],
  },

  {
    id: 'krea-deluxe-organic-wool-1',
    name: 'Organic wool 1',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 26, needle_mm: 4.0 },
    fiber: [{ name: 'merinould', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Organic wool 1 from Krea Deluxe. Composition: 100 % merinould.',
    certifications: ['GOTS'],
  },

  {
    id: 'krea-deluxe-organic-wool-2',
    name: 'Organic wool 2',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 20, needle_mm: 4.0 },
    fiber: [{ name: 'merinould', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Organic wool 2 from Krea Deluxe. Composition: 100 % merinould.',
    certifications: ['GOTS'],
  },

  {
    id: 'krea-deluxe-raw---organic-cotton',
    name: 'Raw - Organic Cotton',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Raw - Organic Cotton from Krea Deluxe. Composition: 100 % bomuld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'krea-deluxe-raw---organic-wool-1',
    name: 'Raw - Organic wool 1',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 23, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Raw - Organic wool 1 from Krea Deluxe. Composition: 100 % uld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'krea-deluxe-raw---organic-wool-2',
    name: 'Raw - Organic wool 2',
    brand: 'Krea Deluxe',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 20, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Raw - Organic wool 2 from Krea Deluxe. Composition: 100 % uld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'bc-garn-brisa',
    name: 'Brisa',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 15, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 42 }, { name: 'alpaca', pct: 35 }, { name: 'uld', pct: 23 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Brisa from BC Garn. Composition: 42 % bomuld, 35 % alpaca, 23 % uld.',
    certifications: ['RAS', 'RWS'],
  },

  {
    id: 'bc-garn-svala',
    name: 'Svala',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'alpaca', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Svala from BC Garn. Composition: 100 % alpaca.',
    certifications: ['RAS'],
  },

  {
    id: 'bc-garn-big-bio-balance-gots',
    name: 'Big bio balance GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 55 }, { name: 'bomuld', pct: 45 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Big bio balance GOTS from BC Garn. Composition: 55 % uld, 45 % bomuld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-bio-balance-gots',
    name: 'bio balance GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 25, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 56 }, { name: 'bomuld', pct: 45 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'bio balance GOTS from BC Garn. Composition: 56 % uld, 45 % bomuld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-babyalpaca',
    name: 'Babyalpaca',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 31, needle_mm: 4.0 },
    fiber: [{ name: 'babyalpaca', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Babyalpaca from BC Garn. Composition: 100 % babyalpaca.',
    certifications: ['RAS'],
  },

  {
    id: 'bc-garn-bio-shetland-gots',
    name: 'Bio Shetland GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Bio Shetland GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-loch-lomond-gots',
    name: 'Loch lomond GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Loch lomond GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-loch-lomond-lace-gots',
    name: 'Loch lomond lace GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 26, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Loch lomond lace GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-lino',
    name: 'Lino',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 21, needle_mm: 4.0 },
    fiber: [{ name: 'hør', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Lino from BC Garn. Composition: 100 % hør.',
    certifications: ['GOTS?'],
  },

  {
    id: 'bc-garn-alba-gots',
    name: 'Alba GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 26, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Alba GOTS from BC Garn. Composition: 100 % bomuld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-jaipur-peace-silk',
    name: 'Jaipur peace silk',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'eri silke', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Jaipur peace silk from BC Garn. Composition: 100 % eri silke.',
    certifications: ['Cruelty free?'],
  },

  {
    id: 'bc-garn-semilla-silkbloom-gots',
    name: 'Semilla silkbloom GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 31, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 75 }, { name: 'silke', pct: 25 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Semilla silkbloom GOTS from BC Garn. Composition: 75 % uld, 25 % silke.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-allino',
    name: 'Allino',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 22, needle_mm: 4.0 },
    fiber: [{ name: 'hør', pct: 50 }, { name: 'bomuld', pct: 50 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Allino from BC Garn. Composition: 50 % hør, 50 % bomuld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'bc-garn-soft-silk',
    name: 'Soft silk',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 20, needle_mm: 4.0 },
    fiber: [{ name: 'Bourette silke', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Soft silk from BC Garn. Composition: 100 % Bourette silke.',
    certifications: ['Cruelty free?'],
  },

  {
    id: 'bc-garn-summer-in-kashmir',
    name: 'Summer in Kashmir',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 90 }, { name: 'kashmir', pct: 10 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Summer in Kashmir from BC Garn. Composition: 90 % bomuld, 10 % kashmir.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-tussah-tweed',
    name: 'Tussah tweed',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'tussahsilke', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Tussah tweed from BC Garn. Composition: 100 % tussahsilke.',
    certifications: ['Cruelty free?'],
  },

  {
    id: 'bc-garn-hamelton-tweed-1gots',
    name: 'Hamelton tweed 1GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 90 }, { name: 'viscose', pct: 10 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Hamelton tweed 1GOTS from BC Garn. Composition: 90 % uld, 10 % viscose.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-hamelton-tweed-2',
    name: 'Hamelton tweed 2',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 12, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 90 }, { name: 'viscose', pct: 10 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Hamelton tweed 2 from BC Garn. Composition: 90 % uld, 10 % viscose.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-semilla-melange-gots',
    name: 'Semilla Melange GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Semilla Melange GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-semilla-gots',
    name: 'Semilla GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 22, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Semilla GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-semilla-pura-gots',
    name: 'Semilla Pura GOTS',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 11, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Semilla Pura GOTS from BC Garn. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'bc-garn-babyalpaca',
    name: 'Babyalpaca',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 31, needle_mm: 4.0 },
    fiber: [{ name: 'alpaca', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Babyalpaca from BC Garn. Composition: 100 % alpaca.',
    certifications: ['RAS?'],
  },

  {
    id: 'bc-garn-luxor-mercerised-cotton',
    name: 'Luxor mercerised cotton',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'merceriseret bomuld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Luxor mercerised cotton from BC Garn. Composition: 100 % merceriseret bomuld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'bc-garn-jaipur-silk-fino',
    name: 'Jaipur silk fino',
    brand: 'BC Garn',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 24, needle_mm: 4.0 },
    fiber: [{ name: 'silke', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Jaipur silk fino from BC Garn. Composition: 100 % silke.',
    certifications: ['Cruelty free?'],
  },

  {
    id: 'kremke-kid-cotton',
    name: 'Kid cotton',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'mohair', pct: 65 }, { name: 'bomuld', pct: 35 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Kid cotton from Kremke. Composition: 65 % mohair, 35 % bomuld.',
    certifications: ['GOTS?'],
  },

  {
    id: 'kremke-the-merry-merino-70-gots',
    name: 'The merry merino 70 GOTS',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 16, needle_mm: 4.0 },
    fiber: [{ name: 'virgin wool', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'The merry merino 70 GOTS from Kremke. Composition: 100 % virgin wool.',
    certifications: ['GOTS'],
  },

  {
    id: 'kremke-the-merry-merino-110-gots',
    name: 'The merry merino 110 GOTS',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'virgin wool', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'The merry merino 110 GOTS from Kremke. Composition: 100 % virgin wool.',
    certifications: ['GOTS'],
  },

  {
    id: 'kremke-the-merry-merino-140-gots',
    name: 'the merry merino 140 GOTS',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 20, needle_mm: 4.0 },
    fiber: [{ name: 'virgin wool', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'the merry merino 140 GOTS from Kremke. Composition: 100 % virgin wool.',
    certifications: ['GOTS'],
  },

  {
    id: 'kremke-the-merry-merino-220',
    name: 'The merry merino 220',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 28, needle_mm: 4.0 },
    fiber: [{ name: 'virgin wool', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'The merry merino 220 from Kremke. Composition: 100 % virgin wool.',
    certifications: ['GOTS'],
  },

  {
    id: 'kremke-silky-kid-rms',
    name: 'Silky kid RMS',
    brand: 'Kremke',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 18, needle_mm: 4.0 },
    fiber: [{ name: 'mohair', pct: 72 }, { name: 'silke', pct: 28 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Silky kid RMS from Kremke. Composition: 72 % mohair, 28 % silke.',
    certifications: ['RMS'],
  },

  {
    id: 'erika-knight-big-vintage-wool-gots',
    name: 'Big vintage wool GOTS',
    brand: 'Erika Knight',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 12, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Big vintage wool GOTS from Erika Knight. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'amano-puno-baby-alpaca-ras',
    name: 'Puno baby alpaca RAS',
    brand: 'Amano',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 22, needle_mm: 4.0 },
    fiber: [{ name: 'alpaca', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Puno baby alpaca RAS from Amano. Composition: 100 % alpaca.',
    certifications: ['RAS'],
  },

  {
    id: 'imagine-baby-alpaca',
    name: 'baby alpaca',
    brand: 'imagine',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 28, needle_mm: 4.0 },
    fiber: [{ name: 'baby alpaca', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'baby alpaca from imagine. Composition: 100 baby alpaca.',
    certifications: ['RAS'],
  },

  {
    id: 'imagine-merino-linen',
    name: 'merino linen',
    brand: 'imagine',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 28, needle_mm: 4.0 },
    fiber: [{ name: 'bomuld', pct: 70 }, { name: 'hør', pct: 30 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'merino linen from imagine. Composition: 70 % bomuld, 30 % hør.',
    certifications: ['GOTS'],
  },

  {
    id: 'lane-mondial-bio-lana-fine',
    name: 'Bio Lana fine',
    brand: 'Lane Mondial',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 23, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Bio Lana fine from Lane Mondial. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

  {
    id: 'lane-mondial-bio-lana',
    name: 'Bio Lana',
    brand: 'Lane Mondial',
    origin: 'Unknown',
    tier: 'mid',
    weight: 'DK',
    gauge: { stitches: 15, needle_mm: 4.0 },
    fiber: [{ name: 'uld', pct: 100 }],
    meters_per_50g: 100,
    price_dkk_50g: 100,
    care: 'Handwash 30C',
    eco: true, vegan: false, mulesing_free: true,
    properties: { softness: 3, warmth: 3, elasticity: 3, drape: 3 },
    buyUrl: '',
    description: 'Bio Lana from Lane Mondial. Composition: 100 % uld.',
    certifications: ['GOTS'],
  },

];

// ─── Pattern Database ──────────────────────────────────────────────
const PATTERNS = [
  {
    id: 'sophie-scarf',
    name: 'Sophie Scarf',
    emoji: '🧣',
    designer: 'PetiteKnit',
    type: 'Tørklæde',
    difficulty: 'Begynder',
    description: 'Let, luftigt tørklæde strikket i mohair holdt dobbelt.',
    originalYarn_id: 'sandnes-tynn-silk-mohair',
    secondaryYarn_id: null,
    totalMeters_M: 600,
    tags: ['tørklæde', 'scarf', 'lace', 'mohair', 'petiteknit'],
    tiers: {
      mid:     [],
      budget:  [],
      premium: [],
    },
  },
];