// ─── Yarn Database ───────────────────────────────────────────────
const YARNS = [
  {
    id: "y1",
    name: "Sandnes Garn Fritidsgarn",
    brand: "Sandnes Garn",
    weight: "Chunky",
    gauge_10cm: 14,
    needle_mm: 6.0,
    fiber: "100% Uld",
    meters_per_100g: 75,
    price_dkk: 89,
    feel: ["varm", "rustik", "robust"],
    tags: ["chunky", "uld", "naturlig"],
    eco: false,
    vegan: false,
  },
  {
    id: "y2",
    name: "Drops Eskimo",
    brand: "Garnstudio DROPS",
    weight: "Chunky",
    gauge_10cm: 14,
    needle_mm: 6.0,
    fiber: "100% Uld",
    meters_per_100g: 50,
    price_dkk: 49,
    feel: ["varm", "blød", "chunky"],
    tags: ["chunky", "uld", "billig"],
    eco: false,
    vegan: false,
  },
  {
    id: "y3",
    name: "Drops Snow",
    brand: "Garnstudio DROPS",
    weight: "Chunky",
    gauge_10cm: 14,
    needle_mm: 6.0,
    fiber: "47% Uld, 53% Alpaka",
    meters_per_100g: 50,
    price_dkk: 59,
    feel: ["blød", "luksus", "let"],
    tags: ["chunky", "alpaka", "blød"],
    eco: false,
    vegan: false,
  },
  {
    id: "y4",
    name: "Pickles Super Chunky",
    brand: "Pickles",
    weight: "Super Chunky",
    gauge_10cm: 10,
    needle_mm: 8.0,
    fiber: "100% Uld",
    meters_per_100g: 40,
    price_dkk: 129,
    feel: ["grov", "hurtig", "rustik"],
    tags: ["super chunky", "uld", "hurtig strik"],
    eco: false,
    vegan: false,
  },
  {
    id: "y5",
    name: "Drops Lima",
    brand: "Garnstudio DROPS",
    weight: "DK / Light Worsted",
    gauge_10cm: 21,
    needle_mm: 4.0,
    fiber: "65% Alpaka, 35% Uld",
    meters_per_100g: 100,
    price_dkk: 49,
    feel: ["blød", "let", "glat"],
    tags: ["DK", "alpaka", "let"],
    eco: false,
    vegan: false,
  },
  {
    id: "y6",
    name: "Isager Alpaca 2",
    brand: "Isager",
    weight: "Fingering / 2ply",
    gauge_10cm: 28,
    needle_mm: 3.0,
    fiber: "50% Merino, 50% Alpaka",
    meters_per_100g: 270,
    price_dkk: 165,
    feel: ["ekstrablød", "fin", "luksus"],
    tags: ["fingering", "merino", "alpaka", "luksus"],
    eco: false,
    vegan: false,
  },
  {
    id: "y7",
    name: "Holst Garn Coast",
    brand: "Holst Garn",
    weight: "Sport / 2ply",
    gauge_10cm: 24,
    needle_mm: 3.5,
    fiber: "75% Uld, 25% Bomuld",
    meters_per_100g: 212,
    price_dkk: 119,
    feel: ["stærk", "holdbar", "let"],
    tags: ["sport", "uld-bomuld", "dansk"],
    eco: false,
    vegan: false,
  },
  {
    id: "y8",
    name: "Onion Organic Cotton",
    brand: "Onion",
    weight: "DK",
    gauge_10cm: 20,
    needle_mm: 4.0,
    fiber: "100% Øko-bomuld",
    meters_per_100g: 110,
    price_dkk: 75,
    feel: ["frisk", "sommer", "glat"],
    tags: ["DK", "bomuld", "øko", "vegan"],
    eco: true,
    vegan: true,
  },
  {
    id: "y9",
    name: "Drops Karisma",
    brand: "Garnstudio DROPS",
    weight: "Worsted / Aran",
    gauge_10cm: 19,
    needle_mm: 4.5,
    fiber: "100% Superwash Uld",
    meters_per_100g: 100,
    price_dkk: 45,
    feel: ["robust", "maskinvask", "klassisk"],
    tags: ["worsted", "superwash", "maskinvask"],
    eco: false,
    vegan: false,
  },
  {
    id: "y10",
    name: "BC Garn Tussah Tweed",
    brand: "BC Garn",
    weight: "Sport",
    gauge_10cm: 24,
    needle_mm: 3.5,
    fiber: "70% Silke, 30% Uld",
    meters_per_100g: 250,
    price_dkk: 149,
    feel: ["glansfuld", "elegant", "stærk"],
    tags: ["sport", "silke", "tweed", "luksus"],
    eco: false,
    vegan: false,
  },
  {
    id: "y11",
    name: "Drops Big Merino",
    brand: "Garnstudio DROPS",
    weight: "Bulky",
    gauge_10cm: 17,
    needle_mm: 5.5,
    fiber: "100% Merino",
    meters_per_100g: 80,
    price_dkk: 69,
    feel: ["blød", "varm", "merino"],
    tags: ["bulky", "merino", "blød"],
    eco: false,
    vegan: false,
  },
  {
    id: "y12",
    name: "CaMaRose Økologisk Yak",
    brand: "CaMaRose",
    weight: "DK",
    gauge_10cm: 22,
    needle_mm: 4.0,
    fiber: "55% Uld, 25% Bambus, 20% Yak",
    meters_per_100g: 230,
    price_dkk: 189,
    feel: ["ekstrablød", "eksotisk", "unik"],
    tags: ["DK", "yak", "bambus", "øko", "luksus"],
    eco: true,
    vegan: false,
  },
];

// ─── Pattern Database ─────────────────────────────────────────────
const PATTERNS = [
  {
    id: "p1",
    name: "Hans",
    emoji: "🧥",
    designer: "PetiteKnit",
    type: "Sweater",
    description: "En klassisk, lidt oversized herretrøje med rund hals. Strikkes oppefra og ned.",
    difficulty: "Øvet begynder",
    yarn_id: "y2",  // Original yarn: DROPS Eskimo
    alternatives: ["y1", "y3", "y11", "y4"],
    tags: ["chunky", "herre", "sweater"],
  },
  {
    id: "p2",
    name: "Campfire Cardigan",
    emoji: "🧶",
    designer: "Tin Can Knits",
    type: "Cardigan",
    description: "Varm og hyggelig cardigan med store kabler. Perfekt til kolde aftener.",
    difficulty: "Erfaren",
    yarn_id: "y11",  // Big Merino
    alternatives: ["y2", "y1", "y3", "y9"],
    tags: ["bulky", "kabel", "cardigan"],
  },
  {
    id: "p3",
    name: "Vikerkaar",
    emoji: "🌈",
    designer: "Helga Isager",
    type: "Sjal",
    description: "Smukt trekantsjal med striber og enkelt mønster. Strikkes fra spids til spids.",
    difficulty: "Begynder",
    yarn_id: "y6",  // Isager Alpaca 2
    alternatives: ["y7", "y10", "y5"],
    tags: ["sjal", "tyndt garn", "mønster"],
  },
  {
    id: "p4",
    name: "Sunday Sweater",
    emoji: "👕",
    designer: "Önling",
    type: "Sweater",
    description: "Let og luftig sweater til sommerdage. Strikkes med bomuldsgarn.",
    difficulty: "Øvet begynder",
    yarn_id: "y8",  // Onion Organic Cotton
    alternatives: ["y5", "y12", "y9"],
    tags: ["DK", "sommer", "bomuld"],
  },
  {
    id: "p5",
    name: "Coastal Cowl",
    emoji: "🪡",
    designer: "Purl Soho",
    type: "Halsedisse",
    description: "Hurtig og tilfredsstillende halsedisse med enkel ribmønster. God nybegynderstrik.",
    difficulty: "Begynder",
    yarn_id: "y7",  // Holst Coast
    alternatives: ["y5", "y10", "y6"],
    tags: ["sport", "ribmønster", "cowl"],
  },
  {
    id: "p6",
    name: "Strikkede Sokker Classic",
    emoji: "🧦",
    designer: "Anni Design",
    type: "Sokker",
    description: "Klassiske sokker strikket på strømpepinde. Solid og varm hverdagssok.",
    difficulty: "Erfaren",
    yarn_id: "y9",  // DROPS Karisma
    alternatives: ["y7", "y6", "y10"],
    tags: ["worsted", "sokker", "maskinvask"],
  },
];
